### Home
GET http://localhost:3000/

### Students
GET http://localhost:3000/students

### Products
GET http://localhost:3000/products

### carBrand
GET http://localhost:3000/carBrand

### Color
GET http://localhost:3000/color

### Error
GET http://localhost:3000/abc